# Shiny - related configuration, settings are using in function runApp, see http://shiny.rstudio.com/reference/shiny/latest/runApp.html 
shiny:
    appDir: js-swc
    host: 127.0.0.1
    # To allow other clients to connect, use the value "0.0.0.0"
    port: 7890
    quiet: No

# logging configuration
logging:
    level: TRACE
#    file: C:/Users/Daniel/sensorweby.log

timeseriesapi:
    endpoint: http://sensorweb.demo.52north.org/sensorwebclient-webapp-stable
    filters:
        service: srv_6d9ccea8d609ecb74d4a512922bb7cee