# Shiny - related configuration, settings are using in function runApp, see http://shiny.rstudio.com/reference/shiny/latest/runApp.html 
shiny:
    appDir: js-swc
    host: 127.0.0.1
    # To allow other clients to connect, use the value "0.0.0.0"
    port: 7890
    quiet: No

# logging configuration
logging:
    level: TRACE
#    file: C:/Users/Daniel/sensorweby.log
